Oss.Romo/Models/Commercial/Commercial_B2BLCStatementReport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Oss.Romo.ViewModels.Commercial;
using Oss.Romo.ViewModels.Reports;

namespace Oss.Romo.Models.Commercial
{
    public class Commercial_B2BLCStatementReport
    {
        public List<ReportDocType> Report { get; set; }
        public List<VmCommercial_B2bLC> BtbList { get; set; }
    }
}

Oss.Romo/Models/Commercial/Commercial_B2BLCStatus.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.CoreProcess.Data;
using System.Linq;
using System.Web;

namespace Oss.Romo.Models.Commercial
{
    public class Commercial_B2BLCStatus : BaseModel
    {
        [DefaultValue(0)]
        public int FirstCreatedBy { get; set; }
        [DefaultValue(0)]
        public int LastEditeddBy { get; set; }

        [StringLength(100, ErrorMessage = "Upto 100 Chracter")]
        [Required(ErrorMessage = "Status is Required")]
        [DisplayName("Status")]
        public string StatusName { get; set; }

        [StringLength(500, ErrorMessage = "Upto 500 Chracter")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
    }
}

Oss.Romo/Models/Commercial/Commercial_B2BLcSupplierPI.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.CoreProcess.Data;
using System.Linq;
using System.Web;

namespace Oss.Romo.Models.Commercial
{
    public class Commercial_B2BLcSupplierPI : BaseModel
    {
        [DefaultValue(0)]
        public int FirstCreatedBy { get; set; }
        [DefaultValue(0)]
        public int LastEditeddBy { get; set; }


        [DisplayName("B2B L/C Supplier PI")]
        [StringLength(20, ErrorMessage = "Upto 20 Chracter")]
        public string Name { get; set; }

        [DisplayName("Description")]
        [DataType(DataType.MultilineText)]
        [StringLength(50, ErrorMessage = "Upto 50 Chracter")]
        public string Description { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Date")]
        public DateTime Date { get; set; }

        [DisplayName("PI")]
        public int? Commercial_PIFK { get; set; }

        [DisplayName("B2b L/C")]
        public int? Commercial_B2bLCFK { get; set; }

        //...........................New Added Code...................................//

        //public Commercial_PI Commercial_PI { get; set; }

        //public Commercial_B2bLC Commercial_B2bLC { get; set; }
    }
}

Oss.Romo/Models/Commercial/Commercial_B2BPaymentInformation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.CoreProcess.Data;
using System.Linq;
using System.Web;

namespace Oss.Romo.Models.Commercial
{
    public class Commercial_B2BPaymentInformation : BaseModel
    {
        [DisplayName("B2B L/C No")]
        public int Commercial_B2bLCFK { get; set; }

        [DisplayName("Supplier Payment")]
        public decimal B2bLCPayment { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Payment Date")]
        public DateTime Date { get; set; }

        [DefaultValue(0)]
        public int FirstCreatedBy { get; set; }

        [DefaultValue(0)]
        public int LastEditeddBy { get; set; }

        public bool IsApproved { get; set; }


        //...........................New Added Code...................................//

        //public Commercial_B2bLC Commercial_B2bLC { get; set; }
    }
}

Oss.Romo/Models/Commercial/Commercial_B2bLC.cs
using Oss.Romo.Models.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.CoreProcess.Data;
using System.Linq;
using System.Web;

namespace Oss.Romo.Models.Commercial
{
    public class Commercial_B2bLC : BaseModel
    {
        [DefaultValue(0)]
        public int FirstCreatedBy { get; set; }
        [DefaultValue(0)]
        public int LastEditeddBy { get; set; }

        [DisplayName("BTB NO")]
        [StringLength(50, ErrorMessage = "Upto 50 Chracter")]
        public string Name { get; set; }
        [DefaultValue(0)]
        [DisplayName("Required Quantity")]
        public decimal? RequiredQuantity { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Date")]
        public DateTime Date { get; set; }

        [DisplayName("BTB Value")]
        [Required(ErrorMessage = "B2B L/C Value is required")]
        public decimal Amount { get; set; }
        
        // Total value is comming from Value and Amendment value(Sum)
        //public decimal TotalValue { get; set; }
        [DefaultValue(0)]
        [DisplayName("Amendment Increase")]
        public decimal AmendmentIncrease { get; set; }
        [DefaultValue(0)]
        [DisplayName("Amendment Decrease")]
        public decimal AmendmentDecrease { get; set; }
      
        [DisplayName("Shipment")]
        public string Shipment { get; set; }        

        [DisplayName("Master L/C")]
        public int? Commercial_MasterLCFK { get; set; }
        [DisplayName("Item")]
        public int Commercial_BTBItemFK { get; set; }

        [DisplayName("UD")]
        public int Commercial_UDFK { get; set; }

        [DisplayName("Supplier")]
        public int Common_SupplierFK { get; set; }
        [DisplayName("Origin")]
        public int Commercial_LCOreginFK { get; set; }
        [DisplayName("Type")]
        public int Commercial_BtBLCTypeFK { get; set; }

        [DisplayName("Unit")]
        [DefaultValue(28)]
        public int? Common_UnitFK { get; set; }

        [DisplayName("Description")]
        [StringLength(200, ErrorMessage = "Upto 200 Chracter")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [DisplayName("Scaned File")]
        [StringLength(200)]
        public string ScanedFile { get; set; }

        [DisplayName("Account Head")]
        public int Acc_AcNameFk { get; set; }
        [DisplayName("Status")]
        [DefaultValue("Running")]
        [StringLength(10, ErrorMessage = "Upto 10 Chracter")]
        public string Status { get; set; } //Add due to requirement--FD 
        public bool IsApproved { get; set; } //Add due to requirement--FD 

        [DefaultValue(1)]
        [DisplayName("Currency Rate")]
        public decimal CurrencyRate { get; set; }
        public int CurrencyType { get; set; }

        //...........................New Added Code...................................//
        //public Commercial_MasterLC Commercial_MasterLC { get; set; }

        //public Commercial_BTBItem Commercial_BTBItem { get; set; }

        //public Commercial_UD Commercial_UD { get; set; }

        //public Common_Supplier Common_Supplier { get; set; }

        //public Commercial_LCOregin Commercial_LCOregin { get; set; }

        //public Commercial_BtBLCType Commercial_BtBLCType { get; set; }

        //public List<Commercial_B2BLcSupplierPI> Commercial_B2BLcSupplierPIs { get; set; }

        //public List<Commercial_B2bLcSupplierPO> Commercial_B2bLcSupplierPOs { get; set; }

        //public List<Commercial_B2BPaymentInformation> Commercial_B2BPaymentInformations { get; set; }

        //public List<Commercial_Import> Commercial_Imports { get; set; }

        //public List<Commercial_MLcSupplierB2BLc> Commercial_MLcSupplierB2BLcs { get; set; }


    }
}

Oss.Romo/Controllers/HelperController.cs
using Oss.Romo.Models;
using Oss.Romo.ViewModels.Account;
using Oss.Romo.ViewModels.Common;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Runtime.InteropServices.ComTypes;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using CrystalDecisions.Web.HtmlReportRender;
using static Oss.Romo.ViewModels.Common.VmForDropDown;
using Oss.Romo.ViewModels.Marketing;
using System.Threading.Tasks;
//using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using Oss.Romo.Models.Planning;
using Oss.Romo.ViewModels.Home;
using Oss.Romo.ViewModels.Planning;
using Oss.Romo.ViewModels.User;
using Oss.Romo.ViewModels.Commercial;

namespace Oss.Romo.Controllers
{
    public class HelperController : Controller
    {
        xOssContext db = new xOssContext();
        VmMis_AdminBoard VmMis_AdminBoard;
        public DataTable DataTable { get; set; }

        public HelperController()
        {
            SessionHandler sessionHandler = new SessionHandler();
            sessionHandler.Adjust();
        }
        public JsonResult GetUserMenuRole(int roleId)
        {
            using (var db = new xOssContext())
            {
                db.Configuration.ProxyCreationEnabled = false;
                return Json(db.User_RoleMenuItem.Where(x => x.User_RoleFK == roleId).ToList(), JsonRequestBehavior.AllowGet);
            }
        }
        //Those Method used for cascading Dropdown

        public JsonResult GetRaw_SubCategory(int? ID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            return Json(db.Raw_SubCategory.Where(p => p.Raw_CategoryFK == ID && p.Active == true && p.IsNew == true), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetRawSubCategory(int? ID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            return Json(db.Raw_SubCategory.Where(p => p.Raw_CategoryFK == ID && p.Active == true && p.IsNew == true && p.ID != 2085
 && p.ID != 2086 && p.ID != 2087), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetRaw_Item(int? ID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            return Json(db.Raw_Item.Where(p => p.Raw_SubCategoryFK == ID).Where(x => x.Active == true && x.IsNew == true), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetRaw_SubCategoryNew(int? ID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            return Json(db.Raw_SubCategory.Where(p => p.Raw_CategoryFK == ID).Where(x => x.Active == true && x.IsNew == true), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetRaw_ItemNew(int? ID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            return Json(db.Raw_Item.Where(p => p.Raw_SubCategoryFK == ID).Where(x => x.Active == true && x.IsNew == true), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetMkt_SubCategory(int? id)
        {
            db.Configuration.ProxyCreationEnabled = false;
            return Json(db.Mkt_SubCategory.Where(p => p.Mkt_CategoryFK == id).Where(x => x.Active == true), JsonRequestBehavior.AllowGet);
        }

        //[HttpGet]
        public JsonResult GetMKT_SubCategory(int? ID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            return Json(db.Mkt_SubCategory.Where(p => p.Mkt_CategoryFK == ID).Where(x => x.Active == true), JsonRequestBehavior.AllowGet);
        }

        //[HttpGet]
        public JsonResult GetMkt_Item(int? ID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            return Json(db.Mkt_Item.Where(p => p.Mkt_SubCategoryFK == ID).Where(x => x.Active == true), JsonRequestBehavior.AllowGet);
        }
        //...Those Method used for cascading Dropdown for Accounting....//


        public JsonResult GetAcc_Chart1DD(int? ID)
        {

            db.Configuration.ProxyCreationEnabled = false;

            return Json(db.Acc_Chart1.Where(a => a.Acc_TypeFK == ID).Where(c => c.Active == true), JsonRequestBehavior.AllowGet);

        }

        public JsonResult GetUserSubMenu(int? ID)
        {

            db.Configuration.ProxyCreationEnabled = false;

            return Json(db.User_SubMenu.Where(a => a.User_MenuFk == ID).Where(c => c.Active == true), JsonRequestBehavior.AllowGet);

        }
        public JsonResult GetAcc_Chart2DD(int? ID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            return Json(db.Acc_Chart2.Where(a => a.Acc_Chart1FK == ID).Where(c => c.Active == true), JsonRequestBehavior.AllowGet);

        }
        public JsonResult GetAcc_NameDD(int? ID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            return Json(db.Acc_AcName.Where(a => a.Acc_Chart2FK == ID).Where(c => c.Active == true), JsonRequestBehavior.AllowGet);

        }
        public JsonResult GetAcc_JournalSlaveDD(int? ID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            return Json(db.Acc_JournalSlave.Where(a => a.Acc_AcNameFK == ID).Where(c => c.Active == true), JsonRequestBehavior.AllowGet);

        }
        public JsonResult GetItemIdByRequisition(int reqSlaveId)
        {
            db.Configuration.ProxyCreationEnabled = false;

            var rawItemId = (from t1 in db.Prod_Requisition_Slave                                      
                                       where t1.Active == true  && t1.ID == reqSlaveId
                                       select new
                                       {
                                           POSlaveId = t1.Mkt_POSlaveFK                                          
                                       }).SingleOrDefault();

            return Json(rawItemId, JsonRequestBehavior.AllowGet);

        }
        

        public JsonResult GetBOMWiseSupplierDD(int? ID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var bOMWiseSupplierList = (from t1 in db.Common_Supplier
                                       join t2 in db.Mkt_BOMSlave
                                       on t1.ID equals t2.Common_SupplierFK
                                       where t1.Active == true
                                       && t2.Mkt_BOMFK == ID
                                       select new
                                       {
                                           ID = t2.Common_SupplierFK,
                                           Name = t1.Name
                                       }).Distinct();
            return Json(bOMWiseSupplierList, JsonRequestBehavior.AllowGet);

        }
        public JsonResult GetBOMByMasterLCDD(int BOMID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var a = (from t1 in db.Mkt_BOM
                     join t2 in db.Common_TheOrder
                     on t1.Common_TheOrderFk equals t2.ID
                     join t3 in db.Commercial_MasterLCBuyerPO
                     on t1.ID equals t3.MKTBOMFK
                     join t4 in db.Commercial_MasterLC
                     on t3.Commercial_MasterLCFK equals t4.ID
                     where t1.Active == true
                     && t2.Active == true
                     && t3.Active == true
                     && t4.Active == true
                     && t1.ID == BOMID
                     select new
                     {
                         BOMID = t3.MKTBOMFK,
                         QPack = t1.QPack,
                         MasterLcID = t4.ID
                     }).Distinct();
            return Json(a, JsonRequestBehavior.AllowGet);
        }
        public int SumOfExistingQPackOrderInvoince = 0;
        //public JsonResult GetBOMExistingQPackInvoinceByMasterLCDD(int bOMID)
        //{
        //    db.Configuration.ProxyCreationEnabled = false;
        //    var a = (from t1 in db.Commercial_InvoiceSlave
        //             join t2 in db.Commercial_Invoice
        //             on t1.Commercial_InvoiceFk equals t2.ID

        //             //join t4 in db.Commercial_MasterLC
        //             //on t2.Commercial_MasterLCFk equals t4.ID
        //             //join t5 in db.Mkt_BOM
        //             //on t1.Mkt_BOMFK equals t5.ID
        //             where t1.Active == true
        //             && t2.Active == true
        //            // && t5.Active == true
        //            // && t4.Active == true
        //             select new
        //             {
        //                 BOMID = t1.Mkt_BOMFK,
        //                 ExistingQPackOrderInvoince = t1.InvoiceQPack,
        //                 //MasterLcID = t4.ID
        //             }).Where(x => x.BOMID == bOMID).Distinct();
        //    return Json(a, JsonRequestBehavior.AllowGet);

        //}
        VmAcc_SupplierPH x = new VmAcc_SupplierPH();
        public JsonResult SupplierPayableValue(int id)
        {
            db = new xOssContext();
            var a = (from Common_Supplier in db.Common_Supplier
                     join t1 in db.Mkt_PO on Common_Supplier.ID equals t1.Common_SupplierFK
                     where Common_Supplier.Active == true && t1.Active == true &&
                     Common_Supplier.ID == id
                     select new VmAcc_SupplierPH
                     {
                         Common_Supplier = Common_Supplier

                     }).Distinct();

            List<VmAcc_SupplierPH> tempDl = new List<VmAcc_SupplierPH>();

            foreach (VmAcc_SupplierPH vmAcc_SupplierPH in a)
            {
                decimal? tempD = x.LCallocationHistory(vmAcc_SupplierPH.Common_Supplier.ID);
                decimal? B2Bpayment = x.GetB2BLCWisePaymentSummary(vmAcc_SupplierPH.Common_Supplier.ID);

Oss.Romo/Views/Commercial/VmCommercial_BTBItemEdit.cshtml
@model Oss.Romo.ViewModels.Commercial.VmCommercial_BTBItem

@{
    Layout = "~/Views/Shared/_LayoutPopup.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.Commercial_BTBItem.ID)


        <div class="form-group">
            @Html.LabelFor(model => model.Commercial_BTBItem.Name, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-6" })
            <div class="col-md-6 col-sm-6 col-xs-6">
                @Html.EditorFor(model => model.Commercial_BTBItem.Name, new { htmlAttributes = new { @class = "form-control ol-md-6 col-xs-6" } })
                @Html.ValidationMessageFor(model => model.Commercial_BTBItem.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Commercial_BTBItem.Description, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-6" })
            <div class="col-md-6 col-sm-6 col-xs-6">
                @Html.EditorFor(model => model.Commercial_BTBItem.Description, new { htmlAttributes = new { @class = "form-control ol-md-6 col-xs-6" } })
                @Html.ValidationMessageFor(model => model.Commercial_BTBItem.Description, "", new { @class = "text-danger" })
            </div>
        </div>
    


        <div class="form-group">
            <div class="col-md-4"></div>
            <div class="col-md-2"></div>
            <p style="margin-left:50px">
                <input type="submit" value="Save" class="btn btn-success" />
                <input type="button" value="Cancel" id="" class="btncancel btn btn-primary" />

            </p>
        </div>

    </div>
}

Oss.Romo/Views/Commercial/VmCommercial_InvoiceSlaveEdit.cshtml
@model Oss.Romo.ViewModels.Commercial.VmCommercial_InvoiceSlave

@{
    Layout = "~/Views/Shared/_LayoutPopup.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="col-md-10">
            @Html.HiddenFor(model => model.Commercial_InvoiceSlave.ID, new { id = "InvoiceSlaveId" })
            @Html.HiddenFor(model => model.Commercial_InvoiceSlave.Commercial_InvoiceFk)
            @Html.HiddenFor(model => model.Commercial_InvoiceSlave.MktBOMFK, new { id = "MktBOMFK" })
        </div>
        @*<div class="form-group" id="divMkt_BOMSlaveFK">
                <label class="control-label col-md-3 col-sm-3 col-xs-6">Style No</label>
                <div class="col-md-6 col-sm-6 col-xs-6">
                    @Html.DropDownListFor(model => model.Commercial_InvoiceSlave.MktBOMFK, ViewBag.DelivaryChallan as SelectList, "--Select Style--", new { @id = "mktBOMFK", @class = "SerchingDropDown form-control col-md-9 col-xs-9" })
                    @Html.ValidationMessageFor(model => model.Commercial_InvoiceSlave.MktBOMFK, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div id="divMkt_POSlaveFK">
            <div class="form-group">
                @Html.LabelFor(model => model.Commercial_InvoiceSlave.Shipment_CNFDelivaryChallanFk, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-6" })

                <div class="col-md-6 col-sm-6 col-xs-6">
                    @Html.DropDownListFor(model => model.Commercial_InvoiceSlave.Shipment_CNFDelivaryChallanFk, ViewBag.DelivaryChallan as SelectList, "--Select Challan No--", new { @id = "shipmentCNFDelivaryChallanFk", @class = "form-control col-md-6 col-xs-6" })
                    @Html.ValidationMessageFor(model => model.Commercial_InvoiceSlave.Shipment_CNFDelivaryChallanFk, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Commercial_InvoiceSlave.Shipment_OrderDeliverdScheduleFK, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-6" })

                <div class="col-md-6 col-sm-6 col-xs-6">
                    @Html.DropDownListFor(model => model.Commercial_InvoiceSlave.Shipment_OrderDeliverdScheduleFK, ViewBag.ShipmentOrderDeliverdSchedule as SelectList, "--Select Deliverd Order--", new { @id = "Shipment_OrderDeliverdScheduleFK", @class = "form-control col-md-6 col-xs-6" })
                    @Html.ValidationMessageFor(model => model.Commercial_InvoiceSlave.Shipment_OrderDeliverdScheduleFK, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <span class="control-label col-md-3 col-sm-3 col-xs-6"><b>Deliverd Quantity</b></span>
                <div class="col-md-6 col-sm-6 col-xs-6">
                    <input type="text" name="ShipDeliverdQuantity" id="shipDeliverdQuantity" class="form-control col-md-9 col-xs-9" readonly="readonly" />
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Commercial_InvoiceSlave.Description, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-6" })
            <div class="col-md-6 col-sm-6 col-xs-6">
                @Html.EditorFor(model => model.Commercial_InvoiceSlave.Description, new { htmlAttributes = new {@id= "txtDescription", @class = "form-control ol-md-6 col-xs-6" } })
                @Html.ValidationMessageFor(model => model.Commercial_InvoiceSlave.Description, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-4"></div>
            <div class="col-md-2"></div>
            <p style="margin-left:50px">
                <input type="submit" value="Save" class="btn btn-success" />
                <input type="button" value="Cancel" id="" class="btncancel btn btn-primary" />

            </p>
        </div>
    </div>
}
<script>







    $(document).ready(function () {

        var invoiceSlaveId = $("#InvoiceSlaveId").val();
       

        $.ajax({
            type: "post",
            url: "@Url.Action("GetDelivaryChallanByID", "Helper")",
            data: { ID: invoiceSlaveId },
            datatype: "json",
            traditional: true,
            success: function (data) {
                $("#shipmentCNFDelivaryChallanFk").val(data.Shipment_CNFDelivaryChallanFk);
                $("#Shipment_OrderDeliverdScheduleFK").val(data.Shipment_OrderDeliverdScheduleFK);
                $("#shipDeliverdQuantity").val(data.DeliverdQty);
            }
        });














        $('#shipmentCNFDelivaryChallanFk').on("change", function (e) {
            var challanId = $('#shipmentCNFDelivaryChallanFk').val();


            $.ajax({
                type: "post",
                url: "@Url.Action("GetScheduleByDelivaryChallan", "Helper")",
                data: { ChallanId: challanId },
                datatype: "json",
                traditional: true,
                success: function (data) {
                    $("#Shipment_OrderDeliverdScheduleFK").empty();
                    if (data.length !== 0) {
                        $("#Shipment_OrderDeliverdScheduleFK").append("<option value='0'>---Select Item---</option>");
                        $.each(data, function (index, row) {
                            console.log(row.value);
                            $("#Shipment_OrderDeliverdScheduleFK").append("<option value='" + row.Value + "'>" + row.Text + "</option>");
                        });

                    }

                }
            });



            $.ajax({
                type: "post",
                url: "@Url.Action("GetBOMByDelivaryChallan", "Helper")",
                data: { ChallanId: challanId },
                datatype: "json",
                traditional: true,
                success: function (data) {
                    $("#MktBOMFK").empty();
                    if (data.length !== 0) {
                        //console.log(data);
                        $("#MktBOMFK").val(data.BOMID);
                    }
                }
            });



        });




        $('#Shipment_OrderDeliverdScheduleFK').on("change", function (e) {
            var id = $('#Shipment_OrderDeliverdScheduleFK').val();
            $.ajax({
                type: "post",
                url: "@Url.Action("GetDelivaryChallanQuantity", "Helper")",
                data: { ID: id },
                datatype: "json",
                traditional: true,
                success: function (data) {
                    $("#shipDeliverdQuantity").empty();
                    if (data.length !== 0) {
                        //console.log(data);
                        $("#shipDeliverdQuantity").val(data.DeliverdQuantity);
                    }
                }
            });
        });
    });





</script>